(use-modules (dom audio)
             (dom canvas)
             (dom console)
             (dom document)
             (dom event)
             (dom image-bitmap)
             (dom response)
             (dom window)
             (goblins actor-lib cell)
             (goblins actor-lib joiners)
             (goblins actor-lib let-on)
             (goblins actor-lib methods)
             (goblins)
             (hoot records)
             (ice-9 match))

(start-client)
