(use-modules (hoot primitives))

(define-syntax define-foreign
    (lambda (stx)
      (define (type-check exp proc-name)
        (define (check param predicate)
          #`(check-type #,param #,predicate '#,proc-name))
        (syntax-case exp (i32 i64 f32 f64 ref null eq string extern)
          ((x i32) (check #'x #'exact-integer?))
          ((x i64) (check #'x #'exact-integer?))
          ((x f32) (check #'x #'real?))
          ((x f64) (check #'x #'real?))
          ((x (ref eq)) #'#t)
          ((x (ref extern)) (check #'x #'external-non-null?))
          ((x (ref null extern)) (check #'x #'external?))
          ((x (ref string)) (check #'x #'string?))
          ((x type) (syntax-violation 'define-foreign "unsupported param type"
                                      stx #'type))))
      (define (import-result-types exp)
        (syntax-case exp (none)
          (none #'())
          (type #'((result type)))))
      (define (result-types exp)
        (syntax-case exp (none i32 i64 f32 f64 ref null string extern)
          (none #'())
          (i32 #'((result i64)))
          (i64 #'((result i64)))
          (f32 #'((result f64)))
          (f64 #'((result f64)))
          ((ref string) #'((result (ref eq))))
          ((ref null string) #'((result (ref eq))))
          ((ref extern) #'((result (ref eq))))
          ((ref null extern) #'((result (ref eq))))
          ((ref eq) #'((result (ref eq))))
          (type (syntax-violation 'define-foreign "unsupported result type"
                                  stx #'type))))
      (define (locals exp)
        (syntax-case exp (none i32 i64 f32 f64 ref null string extern)
          (none #'())
          (i32 #'())
          (i64 #'())
          (f32 #'())
          (f64 #'())
          ((ref string) #'())
          ((ref null string) #'((local $maybe-string (ref null string))))
          ((ref extern) #'())
          ((ref null extern) #'())
          ((ref eq) #'())
          (type (syntax-violation 'define-foreign "unsupported result type"
                                  stx #'type))))
      (define (lift-result exp)
        (syntax-case exp (none i32 i64 f32 f64 ref null string extern)
          ((x none) #'(x))
          ((x i32) #'((i64.extend_i32_s x)))
          ((x i64) #'(x))
          ((x f32) #'((f64.promote_f32 x)))
          ((x f64) #'(x))
          ((x (ref string)) #'((struct.new $string (i32.const 0) x)))
          ((x (ref null string))
           #'((local.set $maybe-string x)
              (if (ref eq)
                  (ref.is_null (local.get $maybe-string))
                  (then (ref.i31 (i32.const 1)))
                  (else (struct.new $string (i32.const 0)
                                    (ref.as_non_null
                                     (local.get $maybe-string)))))))
          ((x (ref extern)) #'((struct.new $extern-ref (i32.const 0) x)))
          ((x (ref null extern)) #'((struct.new $extern-ref (i32.const 0) x)))
          ((x (ref eq)) #'((ref.cast $heap-object x)))
          (type (syntax-violation 'define-foreign "unsupported result type"
                                  stx #'type))))
      (define (fresh-wasm-id prefix)
        (datum->syntax stx (gensym prefix)))
      (define (fresh-wasm-ids prefix lst)
        (map (lambda (_) (fresh-wasm-id prefix)) lst))
      (syntax-case stx (->)
        ((_ proc-name mod name ptype ... -> rtype)
         (and (string? (syntax->datum #'mod)) (string? (syntax->datum #'name)))
         (with-syntax ((iname (fresh-wasm-id "$import-"))
                       ((pname ...) (fresh-wasm-ids "$param-" #'(ptype ...))))
           #`(begin
               (cond-expand
                (guile-vm)
                (hoot
                 (%wasm-import
                  '(func iname (import mod name)
                         (param ptype) ...
                         #,@(import-result-types #'rtype)))))
               (define (proc-name pname ...)
                 #,@(map (lambda (exp) (type-check exp #'proc-name))
                         #'((pname ptype) ...))
                 (%inline-wasm
                  '(func (param pname ptype) ...
                         #,@(result-types #'rtype)
                         #,@(locals #'rtype)
                         #,@(lift-result
                             #'((call iname (local.get pname) ...) rtype)))
                  pname ...))))))))

 (define-syntax cond-expand
    (lambda (x)
      (define (has-req? req)
        (syntax-case req (and or)
          ((and req ...)
           (let lp ((reqs #'(req ...)))
             (or (%eq? reqs '())
                 (and (has-req? (%car reqs))
                      (lp (%cdr reqs))))))
          ((or req ...)
           (let lp ((reqs #'(req ...)))
             (if (%eq? reqs '())
                 #f
                 (or (has-req? (%car reqs))
                     (lp (%cdr reqs))))))
          ((not req)
           (%eq? (%syntax->datum #'not) 'not)
           (if (has-req? #'req) #f #t))
          ((library lib-name)
           (%eq? (%syntax->datum #'library) 'library)
           ;; FIXME: No libraries, for the time being.
           #f)
          (id
           (identifier? #'id)
           (let ((req (%syntax->datum #'id)))
             (let lp ((features (%cons (target-runtime) (features))))
               (if (%eq? features '())
                   #f
                   (or (%eq? req (%car features))
                       (lp (%cdr features)))))))))
      (syntax-case x (else)
        ((_)
         (syntax-violation 'cond-expand "Unfulfilled cond-expand" x))
        ((_ (else body ...))
         #'(begin body ...))
        ((_ (req body ...) more-clauses ...)
         (if (has-req? #'req)
             #'(begin body ...)
             #'(cond-expand more-clauses ...))))))

(define-foreign fill-rect
  "canvas" "fillRect"
  (ref extern) f64 f64 f64 f64 -> none)
