(define (^player/intent bcom direction shooting?)
  (methods ((move new-direction)
            (bcom (^player/intent bcom new-direction shooting?)))
           ((shoot)
            (bcom (^player/intent bcom direction #t)))
           ((direction)
            direction)
           ((shooting?)
            shooting?)
           ((clear-shooting)
            (bcom (^player/intent bcom direction #f)))))

(define (^robot/intent bcom direction shooting?)
  (methods ((move new-direction)
            (bcom (^robot/intent bcom new-direction shooting?)))
           ((shoot)
            (bcom (^robot/intent bcom direction #t)))
           ((direction)
            direction)
           ((shooting?)
            shooting?)
           ((clear-shooting)
            (bcom (^robot/intent bcom direction #f)))))

(define (^spider/intent bcom direction)
  (methods ((move new-direction)
            (bcom (^spider/intent bcom new-direction)))
           (direction)
           direction))

(define (^blob/intent bcom direction)
  (methods ((move new-direction)
            (bcom (^blob/intent bcom new-direction)))
           (direction)
           direction))
